"""
_generate_context.py — Generate agent-memory/CONTEXT.md
=========================================================
Called by run.bat before launching OpenCode.
Merges identity.md + state.json + recent session + facts.
The resulting CONTEXT.md is read as OpenCode initial context.
"""
import json, time, sys
from pathlib import Path

ROOT = Path(__file__).parent.resolve()
MEMORY = ROOT / "agent-memory"
IDENTITY = MEMORY / "identity.md"
STATE = MEMORY / "state.json"
FACTS = MEMORY / "FACTS.json"
SESSIONS = MEMORY / "sessions"
CONTEXT = MEMORY / "CONTEXT.md"


def get_recent_logs(n=3):
    """Get summaries of recent session logs (last N sessions)."""
    logs = sorted(SESSIONS.glob("*.md"), reverse=True)[:n]
    if not logs:
        return "(no previous sessions)"
    parts = []
    for log in logs:
        text = log.read_text(encoding="utf-8", errors="replace")
        # grab first 5 meaningful lines
        lines = [l for l in text.split("\n") if l.strip() and not l.startswith("#")]
        summary = " ".join(lines[:5])[:300]
        parts.append(f"- {log.stem}: {summary}")
    return "\n".join(parts)


def get_state_summary():
    """Get current provider status from state.json."""
    if not STATE.exists():
        return "(state unknown — run probe.py first)"
    s = json.loads(STATE.read_text(encoding="utf-8"))
    lines = []
    for pid, info in s.get("providers", {}).items():
        tag = "ONLINE" if info["online"] else "OFFLINE"
        lines.append(f"  {pid}: {tag} — {info.get('msg', '')}")
    return f"Last probe: {s.get('last_probe', '?')}\n" + "\n".join(lines)


def get_facts():
    """Get key facts from FACTS.json."""
    if not FACTS.exists():
        return "(no facts stored)"
    data = json.loads(FACTS.read_text(encoding="utf-8"))
    facts = data.get("facts", {})
    if not facts:
        return "(no facts stored)"
    return "\n".join(f"- {k}: {v}" for k, v in facts.items())


def main():
    # read identity
    identity = IDENTITY.read_text(encoding="utf-8") if IDENTITY.exists() else ""

    # gather context
    state = get_state_summary()
    facts = get_facts()
    recent = get_recent_logs()

    now = time.strftime("%Y-%m-%d %H:%M:%S")

    content = f"""## Session Context — {now}

{identity}

## Current Provider Status
{state}

## Stored Facts
{facts}

## Recent Activity
{recent}

---
This file is auto-generated by _generate_context.py.
Edit identity.md to change agent behavior.
Use memory.bat add/recall to manage facts.
"""

    CONTEXT.write_text(content, encoding="utf-8")
    print(f"[OK] CONTEXT.md generated ({len(content)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
