@echo off
:: Auto-generated by probe.py at 2026-06-08 22:30:18
:: DO NOT EDIT — regenerated on every probe

set PROV_LLAMACPP_ID=llamacpp
set PROV_LLAMACPP_ONLINE=0
set PROV_LLAMACPP_DISPLAY=Qwen2.5-Coder-3B (llama.cpp, CPU-tuned)
set PROV_LLAMACPP_BASE_URL=http://127.0.0.1:11435/v1
set PROV_LLAMACPP_API_KEY=llama-local-key
set PROV_LLAMACPP_MODEL=qwen2.5-coder:3b-instruct-q4_K_M
set PROV_LLAMACPP_PORT=11435
set PROV_LLAMACPP_MODEL_PATH=ollama-models\qwen2.5-coder-3b-instruct-q4_k_m.gguf
set PROV_LLAMACPP_EXECUTABLE=tools\llama-server.exe

set PROV_COUNT=1
set PROV_ONLINE_COUNT=0